build and publish symbols package (`snupkg`) along with `nupkg` (#10)
* add editorconfig options for xml files

* separate inputs for nuget and github release, include symbol files in nuget

* add optional version override

* add link to release notes

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -3,14 +3,21 @@ name: Publish packages on Nuget
 on:
   workflow_dispatch:
     inputs:
-      publish-package:
-        description: "Build or Build and Publish?"
+      publish-github-release:
+        description: "Publish GitHub Release"
         required: true
-        type: choice
-        default: "Build"
-        options:
-          - "Build"
-          - "Build and Publish"
+        type: boolean
+        default: false
+      publish-nuget:
+        description: "Publish to NuGet"
+        required: true
+        type: boolean
+        default: false
+      package-version-override:
+        description: "Package version override (optional, x.y.z)"
+        required: false
+        type: string
+        default: ""
 
 permissions: {}
 
@@ -24,11 +31,15 @@ jobs:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       - id: package
         run: |
-          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-            echo "Invalid tag format: $GITHUB_REF, must be in the form vMAJOR.MINOR.PATCH"
-            exit 1
+          if [[ -n "${{ github.event.inputs.package-version-override }}" ]]; then
+            PACKAGE_VERSION="${{ github.event.inputs.package-version-override }}"
+          else
+            if [[ ! "$GITHUB_REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+              echo "Invalid tag format: $GITHUB_REF, must be in the form vMAJOR.MINOR.PATCH"
+              exit 1
+            fi
+            PACKAGE_VERSION="${GITHUB_REF#refs/tags/v}"
           fi
-          PACKAGE_VERSION="${GITHUB_REF#refs/tags/v}"
 
           echo "package-version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
       - id: serverlesscompatbinary
@@ -62,9 +73,11 @@ jobs:
       - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
         with:
           name: build
-          path: Datadog.Serverless/bin/Release/Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.nupkg
-  publish:
-    if: ${{ github.event.inputs.publish-package == 'Build and Publish' }}
+          path: |
+            Datadog.Serverless/bin/Release/Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.nupkg
+            Datadog.Serverless/bin/Release/Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.snupkg
+  publish-nuget:
+    if: ${{ github.event.inputs.publish-nuget == 'true' }}
     needs: [downloadbinaries, build]
     runs-on: ubuntu-latest
     env:
@@ -76,11 +89,13 @@ jobs:
       - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 #4.3.1
         with:
           dotnet-version: "9.0.x"
-      - run: dotnet nuget push Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
-  release:
-    if: ${{ github.event.inputs.publish-package == 'Build and Publish' }}
+      - run: |
+          dotnet nuget push Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+          dotnet nuget push Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+  create-github-release:
+    if: ${{ github.event.inputs.publish-github-release == 'true' }}
     runs-on: ubuntu-latest
-    needs: [downloadbinaries, build, publish]
+    needs: [downloadbinaries, build]
     permissions:
       contents: write
     env:
@@ -89,8 +104,11 @@ jobs:
     steps:
       - uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
         with:
-          body: "Uses [${{ env.SERVERLESS_COMPAT_VERSION }}](https://github.com/DataDog/serverless-components/releases/tag/${{ env.SERVERLESS_COMPAT_VERSION }}) of the Serverless Compatibility Layer binary."
+          body: "Install [Datadog.Serverless.Compat](https://www.nuget.org/packages/Datadog.Serverless.Compat/${{ env.PACKAGE_VERSION }}) from NuGet.\n\nUses [${{ env.SERVERLESS_COMPAT_VERSION }}](https://github.com/DataDog/serverless-components/releases/tag/${{ env.SERVERLESS_COMPAT_VERSION }}) of the Serverless Compatibility Layer binary."
           draft: true
           tag_name: "v${{ env.PACKAGE_VERSION }}"
           generate_release_notes: true
           make_latest: true
+          files: |
+            Datadog.Serverless/bin/Release/Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.nupkg
+            Datadog.Serverless/bin/Release/Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.snupkg
