chore: use dotnet pack -p:Version to set package version (#7)
* dynamically set package version from git tag

* update version regex to accommodate suffixes

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -24,7 +24,12 @@ jobs:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       - id: package
         run: |
-          PACKAGE_VERSION=$(awk -F '[<>]' '/<Version>/{print $3; exit}' Datadog.Serverless/Datadog.Serverless.Compat.csproj)
+          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
+            echo "Invalid tag format: $GITHUB_REF, must be in the form vMAJOR.MINOR.PATCH"
+            exit 1
+          fi
+          PACKAGE_VERSION="${GITHUB_REF#refs/tags/v}"
+
           echo "package-version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
       - id: serverlesscompatbinary
         run: |
@@ -53,7 +58,7 @@ jobs:
       - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 #4.3.1
         with:
           dotnet-version: "9.0.x"
-      - run: cd Datadog.Serverless && dotnet pack -c Release
+      - run: cd Datadog.Serverless && dotnet pack -p:Version=${{ env.PACKAGE_VERSION }} -c Release
       - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
         with:
           name: build
